# Generated by Django 2.1 on 2018-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20180917_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ci',
            field=models.IntegerField(default=0),
        ),
    ]
