# Generated by Django 2.1 on 2018-09-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_secretary_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
    ]
