# Generated by Django 2.1 on 2018-10-08 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_career_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newMark', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteAprobado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExamLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TitleValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidatedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='career',
            old_name='amount',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='secretary',
            old_name='telefon_number',
            new_name='telephone_number',
        ),
        migrations.RemoveField(
            model_name='career',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='number',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='id',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='classroom',
            name='IdC',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='secretary',
            name='CIS',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='student',
            name='CI',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=2, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='student',
            name='telephone_number',
            field=models.IntegerField(default=0, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=50, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=20, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='apellidos'),
        ),
        migrations.AddField(
            model_name='validatedstudent',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Secretary'),
        ),
        migrations.AddField(
            model_name='validatedstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='titlevalidation',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.ClassRoom'),
        ),
        migrations.AddField(
            model_name='titlevalidation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='examlocation',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.ClassRoom'),
        ),
        migrations.AddField(
            model_name='examlocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='estudianteaprobado',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Career'),
        ),
        migrations.AddField(
            model_name='estudianteaprobado',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='claim',
            name='student',
            field=models.ForeignKey(on_delete='CASCADE', to='students.Student'),
        ),
    ]
