# Generated by Django 2.1 on 2018-10-09 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20181008_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='newMark',
            new_name='new_grade',
        ),
        migrations.RenameField(
            model_name='validatedstudent',
            old_name='mark',
            new_name='grade',
        ),
    ]
