# Generated by Django 2.1 on 2018-10-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20181031_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_end',
            field=models.DateField(verbose_name='fecha de final'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_start',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_end',
            field=models.DateField(verbose_name='fecha final'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_start',
            field=models.DateField(verbose_name='fecha inicio'),
        ),
    ]
