# Generated by Django 2.1 on 2018-11-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20181031_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Secretary', verbose_name='secretaria')),
            ],
            options={
                'verbose_name': 'Turno Asignado',
                'verbose_name_plural': 'Turnos Asignados',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='día')),
                ('time', models.TimeField(verbose_name='time')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.AddField(
            model_name='assignturn',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Turn', verbose_name='turno'),
        ),
    ]
