# Generated by Django 2.1 on 2018-11-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20181111_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='telephone_number',
        ),
    ]
