# Generated by Django 2.1 on 2018-11-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_student_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telephone_number',
            field=models.IntegerField(default=0, verbose_name='teléfono'),
        ),
    ]
