# Generated by Django 2.1 on 2018-11-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20181112_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeTurns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField(verbose_name='día de inicio')),
                ('end_day', models.DateField(verbose_name='día final')),
                ('secretary_amount', models.IntegerField(verbose_name='cantidad de secretarias')),
                ('start_time', models.TimeField(verbose_name='horario inicial')),
                ('end_time', models.TimeField(verbose_name='horario final')),
            ],
        ),
    ]
