# Generated by Django 2.1 on 2018-11-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_maketurns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maketurns',
            options={'verbose_name': 'Turno Horario', 'verbose_name_plural': 'Turnos Horarios'},
        ),
    ]
