# Generated by Django 2.1 on 2018-12-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_auto_20181129_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignturn',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='assignturn',
            name='turn',
        ),
        migrations.AddField(
            model_name='turn',
            name='assign',
            field=models.BooleanField(default=True, verbose_name='asignado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn',
            name='secretary',
            field=models.IntegerField(default=1, verbose_name='secretaria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AssignTurn',
        ),
    ]
