# Generated by Django 2.1.4 on 2019-02-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20190206_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ocupation',
            field=models.CharField(choices=[('1', 'Dirigente'), ('2', 'Profesional'), ('3', 'Tecnico'), ('4', 'Administrativo'), ('5', 'Trabajador de los servicios'), ('6', 'Obrero'), ('7', 'Campesino'), ('8', 'Ama de casa'), ('9', 'Otra situación')], default='3', max_length=20, verbose_name='ocupacion'),
        ),
        migrations.AddField(
            model_name='student',
            name='procedence',
            field=models.CharField(choices=[('1', 'IPU'), ('2', 'Politecnico'), ('3', 'FOC'), ('4', 'Otro')], default='1', max_length=20, verbose_name='procedencia escolar'),
        ),
        migrations.AddField(
            model_name='student',
            name='town',
            field=models.CharField(default='Playa', max_length=50, verbose_name='municipio'),
        ),
        migrations.AddField(
            model_name='student',
            name='vinculation',
            field=models.BooleanField(default=True, verbose_name='vinculación'),
        ),
        migrations.AddField(
            model_name='student',
            name='workSec',
            field=models.CharField(choices=[('1', 'Estatal'), ('2', 'Privado'), ('3', 'Cooperativo'), ('4', 'Mixto o Extranjero')], default='1', max_length=20, verbose_name='sector laboral'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='teléfono'),
        ),
    ]
