# Generated by Django 2.1.4 on 2019-02-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_student_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='telephone_number',
            new_name='tel',
        ),
    ]
